import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { INVEXA_LOGO_BASE64 } from "../assets/logoBase64";
import { apiFetch } from "../api/client";

type Transaction = {
  date: string;
  type: "BUY" | "SELL" | "DEPOSIT";
  description: string;
  ticker?: string;
  quantity?: number;
  rate?: number;
  amount: number;
};

type Input = {
  user: { id: string; username: string; email: string };
  token: string;
};

function inr(n: number) {
  return "Rs. " + n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export async function downloadAccountStatementPdf({ user, token }: Input) {
  const { transactions } = await apiFetch<{ transactions: Transaction[] }>("/portfolio/transactions", {}, token);

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  doc.addImage(INVEXA_LOGO_BASE64, "PNG", margin, 30, 46, 46);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Invexa", margin + 56, 52);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90);
  doc.text("Account Statement", margin + 56, 68);

  doc.setDrawColor(220);
  doc.line(margin, 92, pageWidth - margin, 92);

  const generatedOn = new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
  doc.setTextColor(20);
  doc.setFontSize(11);
  let y = 116;
  const rows: Array<[string, string]> = [
    ["Account Holder", user.username],
    ["Account ID", user.id],
    ["Email", user.email],
    ["Statement Generated", generatedOn]
  ];
  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(value), margin + 140, y);
    y += 18;
  });

  y += 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Transaction History", margin, y);
  y += 16;

  if (transactions.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("No transactions yet.", margin, y + 16);
  } else {
    autoTable(doc, {
      startY: y + 6,
      margin: { left: margin, right: margin },
      head: [["Sr.No", "Type", "Description", "Date", "Amount"]],
      body: transactions.map((t, idx) => [
        String(idx + 1),
        t.type,
        t.description,
        new Date(t.date).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }),
        (t.type === "SELL" || t.type === "DEPOSIT" ? "+" : "-") + inr(Math.abs(t.amount))
      ]),
      theme: "striped",
      headStyles: { fillColor: [17, 20, 23], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 9, cellPadding: 6 },
      columnStyles: { 2: { cellWidth: 220 } },
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 4) {
          const t = transactions[data.row.index];
          data.cell.styles.textColor = t.type === "BUY" ? [209, 60, 60] : [31, 157, 110];
        }
        if (data.section === "body" && data.column.index === 1) {
          const t = transactions[data.row.index];
          data.cell.styles.textColor = t.type === "BUY" ? [209, 60, 60] : t.type === "SELL" ? [31, 157, 110] : [90, 90, 90];
          data.cell.styles.fontStyle = "bold";
        }
      }
    });
  }

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      "This is a virtual paper-trading statement generated by Invexa. No real currency is involved.",
      margin,
      doc.internal.pageSize.getHeight() - 24
    );
  }

  doc.save(`invexa-statement-${user.username}-${new Date().toISOString().slice(0, 10)}.pdf`);
}
